# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a71-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a71 m51,$(TARGET_DEVICE)),)

endif
